export const FORMATIONS_SLOTS: Record<string, { label: string; role: string; x: number; y: number }[]> = {
  '4-4-2': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MI', role: 'Interior Izquierdo', x: 18, y: 44 },
    { label: 'MC', role: 'Medio Izquierdo', x: 38, y: 46 },
    { label: 'MC', role: 'Medio Derecho', x: 62, y: 46 },
    { label: 'MD', role: 'Interior Derecho', x: 82, y: 44 },
    { label: 'DC', role: 'Delantero Izquierdo', x: 35, y: 20 },
    { label: 'DC', role: 'Delantero Derecho', x: 65, y: 20 },
  ],
  '4-3-3': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MC', role: 'Medio Izquierdo', x: 28, y: 46 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 54 },
    { label: 'MC', role: 'Medio Derecho', x: 72, y: 46 },
    { label: 'EI', role: 'Extremo Izquierdo', x: 22, y: 22 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 16 },
    { label: 'ED', role: 'Extremo Derecho', x: 78, y: 22 },
  ],
  '3-5-2': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'DFC', role: 'Central Izquierdo', x: 28, y: 71 },
    { label: 'DFC', role: 'Central', x: 50, y: 73 },
    { label: 'DFC', role: 'Central Derecho', x: 72, y: 71 },
    { label: 'MI', role: 'Interior Izquierdo', x: 15, y: 46 },
    { label: 'MC', role: 'Medio Izquierdo', x: 35, y: 49 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 57 },
    { label: 'MC', role: 'Medio Derecho', x: 65, y: 49 },
    { label: 'MD', role: 'Interior Derecho', x: 85, y: 46 },
    { label: 'DC', role: 'Delantero Izquierdo', x: 35, y: 20 },
    { label: 'DC', role: 'Delantero Derecho', x: 65, y: 20 },
  ],
  '4-2-3-1': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MCD', role: 'Pivote Izquierdo', x: 35, y: 54 },
    { label: 'MCD', role: 'Pivote Derecho', x: 65, y: 54 },
    { label: 'MI', role: 'Interior Izquierdo', x: 20, y: 34 },
    { label: 'MCO', role: 'Mediapunta', x: 50, y: 32 },
    { label: 'MD', role: 'Interior Derecho', x: 80, y: 34 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 15 },
  ],
  '3-4-3': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'DFC', role: 'Central Izquierdo', x: 28, y: 71 },
    { label: 'DFC', role: 'Central', x: 50, y: 73 },
    { label: 'DFC', role: 'Central Derecho', x: 72, y: 71 },
    { label: 'MI', role: 'Interior Izquierdo', x: 15, y: 48 },
    { label: 'MC', role: 'Medio Izquierdo', x: 38, y: 52 },
    { label: 'MC', role: 'Medio Derecho', x: 62, y: 52 },
    { label: 'MD', role: 'Interior Derecho', x: 85, y: 48 },
    { label: 'EI', role: 'Extremo Izquierdo', x: 20, y: 20 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 15 },
    { label: 'ED', role: 'Extremo Derecho', x: 80, y: 20 },
  ],
  '4-1-4-1': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 56 },
    { label: 'MI', role: 'Interior Izquierdo', x: 18, y: 40 },
    { label: 'MC', role: 'Medio Izquierdo', x: 38, y: 42 },
    { label: 'MC', role: 'Medio Derecho', x: 62, y: 42 },
    { label: 'MD', role: 'Interior Derecho', x: 82, y: 40 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 16 },
  ],
  '5-3-2': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 15, y: 66 },
    { label: 'DFC', role: 'Central Izquierdo', x: 32, y: 72 },
    { label: 'DFC', role: 'Central', x: 50, y: 74 },
    { label: 'DFC', role: 'Central Derecho', x: 68, y: 72 },
    { label: 'LD', role: 'Lateral Derecho', x: 85, y: 66 },
    { label: 'MC', role: 'Medio Izquierdo', x: 30, y: 48 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 52 },
    { label: 'MC', role: 'Medio Derecho', x: 70, y: 48 },
    { label: 'DC', role: 'Delantero Izquierdo', x: 38, y: 20 },
    { label: 'DC', role: 'Delantero Derecho', x: 62, y: 20 },
  ],
  '5-4-1': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 15, y: 66 },
    { label: 'DFC', role: 'Central Izquierdo', x: 32, y: 72 },
    { label: 'DFC', role: 'Central', x: 50, y: 74 },
    { label: 'DFC', role: 'Central Derecho', x: 68, y: 72 },
    { label: 'LD', role: 'Lateral Derecho', x: 85, y: 66 },
    { label: 'MI', role: 'Interior Izquierdo', x: 20, y: 46 },
    { label: 'MC', role: 'Medio Izquierdo', x: 40, y: 48 },
    { label: 'MC', role: 'Medio Derecho', x: 60, y: 48 },
    { label: 'MD', role: 'Interior Derecho', x: 80, y: 46 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 18 },
  ],
  '4-4-2 Diamante': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 55 },
    { label: 'MC', role: 'Medio Izquierdo', x: 28, y: 45 },
    { label: 'MC', role: 'Medio Derecho', x: 72, y: 45 },
    { label: 'MCO', role: 'Mediapunta', x: 50, y: 35 },
    { label: 'DC', role: 'Delantero Izquierdo', x: 38, y: 18 },
    { label: 'DC', role: 'Delantero Derecho', x: 62, y: 18 },
  ],
  '4-3-2-1 (Árbol)': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MC', role: 'Medio Izquierdo', x: 28, y: 52 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 55 },
    { label: 'MC', role: 'Medio Derecho', x: 72, y: 52 },
    { label: 'MP', role: 'Mediapunta Izquierdo', x: 35, y: 32 },
    { label: 'MP', role: 'Mediapunta Derecho', x: 65, y: 32 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 15 },
  ],
  '3-1-4-2': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'DFC', role: 'Central Izquierdo', x: 28, y: 71 },
    { label: 'DFC', role: 'Central', x: 50, y: 73 },
    { label: 'DFC', role: 'Central Derecho', x: 72, y: 71 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 58 },
    { label: 'MI', role: 'Interior Izquierdo', x: 15, y: 45 },
    { label: 'MC', role: 'Medio Izquierdo', x: 38, y: 42 },
    { label: 'MC', role: 'Medio Derecho', x: 62, y: 42 },
    { label: 'MD', role: 'Interior Derecho', x: 85, y: 45 },
    { label: 'DC', role: 'Delantero Izquierdo', x: 38, y: 20 },
    { label: 'DC', role: 'Delantero Derecho', x: 62, y: 20 },
  ],
  '4-5-1': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MI', role: 'Interior Izquierdo', x: 20, y: 42 },
    { label: 'MC', role: 'Medio Izquierdo', x: 35, y: 46 },
    { label: 'MC', role: 'Mediocentro', x: 50, y: 48 },
    { label: 'MC', role: 'Medio Derecho', x: 65, y: 46 },
    { label: 'MD', role: 'Interior Derecho', x: 80, y: 42 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 18 },
  ],
  '3-4-2-1': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'DFC', role: 'Central Izquierdo', x: 28, y: 71 },
    { label: 'DFC', role: 'Central', x: 50, y: 73 },
    { label: 'DFC', role: 'Central Derecho', x: 72, y: 71 },
    { label: 'MI', role: 'Interior Izquierdo', x: 15, y: 48 },
    { label: 'MC', role: 'Medio Izquierdo', x: 38, y: 52 },
    { label: 'MC', role: 'Medio Derecho', x: 62, y: 52 },
    { label: 'MD', role: 'Interior Derecho', x: 85, y: 48 },
    { label: 'MP', role: 'Mediapunta Izquierdo', x: 35, y: 32 },
    { label: 'MP', role: 'Mediapunta Derecho', x: 65, y: 32 },
    { label: 'DC', role: 'Delantero Centro', x: 50, y: 15 },
  ],
  '4-1-3-2': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'LI', role: 'Lateral Izquierdo', x: 18, y: 68 },
    { label: 'DFC', role: 'Central Izquierdo', x: 38, y: 71 },
    { label: 'DFC', role: 'Central Derecho', x: 62, y: 71 },
    { label: 'LD', role: 'Lateral Derecho', x: 82, y: 68 },
    { label: 'MCD', role: 'Pivote', x: 50, y: 56 },
    { label: 'MI', role: 'Interior Izquierdo', x: 20, y: 42 },
    { label: 'MCO', role: 'Mediapunta', x: 50, y: 40 },
    { label: 'MD', role: 'Interior Derecho', x: 80, y: 42 },
    { label: 'DC', role: 'Delantero Izquierdo', x: 38, y: 20 },
    { label: 'DC', role: 'Delantero Derecho', x: 62, y: 20 },
  ],
  '3-4-1-2': [
    { label: 'GK', role: 'Portero', x: 50, y: 88 },
    { label: 'DFC', role: 'Central Izquierdo', x: 28, y: 71 },
    { label: 'DFC', role: 'Central', x: 50, y: 73 },
    { label: 'DFC', role: 'Central Derecho', x: 72, y: 71 },
    { label: 'MI', role: 'Interior Izquierdo', x: 15, y: 48 },
    { label: 'MC', role: 'Medio Izquierdo', x: 38, y: 52 },
    { label: 'MC', role: 'Medio Derecho', x: 62, y: 52 },
    { label: 'MD', role: 'Interior Derecho', x: 85, y: 48 },
    { label: 'MCO', role: 'Mediapunta', x: 50, y: 35 },
    { label: 'DC', role: 'Delantero Izquierdo', x: 38, y: 18 },
    { label: 'DC', role: 'Delantero Derecho', x: 62, y: 18 },
  ]
};
